config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cabins
  resources :payments
  resources :rates
  resources :rolls
  resources :vehicles

  devise_scope :user do
    authenticated :user do
      root "vehicles#index"
      #root "devise/sessions#destroy"
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :user_unregistered
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rate.rb
class Rate < ApplicationRecord
	belongs_to :vehicle

	validates :price, :from, :to, presence: true
	validates :price, numericality: true
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /rates or /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1 or /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates or /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: "Rate was successfully created." }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1 or /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: "Rate was successfully updated." }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1 or /rates/1.json
  def destroy
    count = 0

    for i in Vehicle.all
      for r in Roll.all
        for f in Payment.all
          if (i.roll == r) and (i.rate_id == @rate.id) and (f.roll == r)
            count =  count + 1
          end
        end
      end
    end

    if count == 0
      @rate.destroy
      respond_to do |format|
        format.html { redirect_to rates_url, notice: "Rate was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to rates_url, notice: "Rate was not destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rate_params
      params.require(:rate).permit(:price, :from, :to, :vehicle_id)
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.erb
<%= form_with(model: rate) do |form| %>
  <% if rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
        <% rate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vehicle_id %>
    <%= form.collection_select(:vehicle_id, Vehicle.all, :id, :patent) %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.datetime_select :from %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.datetime_select :to %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing Rate</h1>

<%= render 'form', rate: @rate %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rates</h1>

<table>
  <thead>
    <tr>
      <th>Vehicle type</th>
      <th>Price</th>
      <th>From</th>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rates.each do |rate| %>
      <tr>
        <td><%= rate.vehicle.patent %></td>
        <td><%= rate.price %></td>
        <td><%= rate.from %></td>
        <td><%= rate.to %></td>
        <% if current_user.role == "administrador" %>
          <td><%= link_to 'Show', rate %></td>
          <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
          <td><%= link_to 'Destroy', rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/new.html.erb
<h1>New Rate</h1>

<%= render 'form', rate: @rate %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @rate.price %>
</p>

<p>
  <strong>From:</strong>
  <%= @rate.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @rate.to %>
</p>

<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>