config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cabins
  resources :payments
  resources :rates
  resources :rolls
  resources :vehicles

  devise_scope :user do
    authenticated :user do
      root "vehicles#index"
      #root "devise/sessions#destroy"
    end

    unauthenticated :user do
      root "devise/sessions#new", as: :user_unregistered
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peaje</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    | <%= link_to 'Payments', payments_path, class: "back-but"%> |
    <%= link_to 'Vehicles', vehicles_path, class: "back-but"%> |
    <%= link_to 'Cabins', cabins_path, class: "back-but"%> |
    <%= link_to 'Rolls', rolls_path, class: "back-but"%> |
    <%= link_to 'Rates', rates_path, class: "back-but"%> |
    <% if current_user %>
      <%= link_to "Log out►", destroy_user_session_path, method: :delete, class: "logout" %> |
    <% else %>
      <%= link_to "Log in►", new_user_session_path, class: "loginb" %> |
      <%= link_to "Sign up►", new_user_registration_path, class: "loginb" %> |
    <% end %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>